name: CD

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v7

      - uses: pnpm/action-setup@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: pnpm
          registry-url: https://registry.npmjs.org

      - run: pnpm install --frozen-lockfile
      - run: pnpm lint
      - run: pnpm type:check
      - run: pnpm test
      - run: pnpm build
      - run: pnpm pack:check
      - run: pnpm publish --no-git-checks --access public --provenance
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
